server:
  port: 8888
spring:
  application:
    name: external-configuration
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Maksering/java-configs.git
          search-paths: /config-files/
