server:
  port: 8888
spring:
  application:
    name: external-configuration
  cloud:
    config:
      server:
        git:
          uri:
          username:
          password:
          search-paths:
